
package com.Idms.main;

import com.Idms.beans.Receipt;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import com.Idms.beans.Doctor;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Jitesh
 */
public class DoctorDisplay extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    CardLayout cardLayout = new CardLayout();
    CardLayout settingLayout = new CardLayout();
    public DoctorDisplay(Doctor doctor) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.doctor = doctor;
        if(doctor.getPatient()!=null) {
            allDocPatientData = doctor.getPatient();
            docPatientData = sortedList("OneDay");
        }
        initComponents();
        cardLayout = (CardLayout)(display.getLayout());
        settingLayout = (CardLayout)(settingDisplayPanel.getLayout());
        displayProfile();
        appointmentNumValue.setText(String.valueOf(docPatientData.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        display = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        appointmentViews = new javax.swing.JPanel();
        tableViewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        appointmentNumValue = new javax.swing.JLabel();
        appointementNumLabel = new javax.swing.JLabel();
        oneMonthView = new javax.swing.JLabel();
        oneDayView = new javax.swing.JLabel();
        fiveDayView = new javax.swing.JLabel();
        sixMonthView = new javax.swing.JLabel();
        oneYearView = new javax.swing.JLabel();
        indicatorDate = new javax.swing.JLabel();
        prescriptionPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        patientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        patientPhNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        patientAge = new javax.swing.JTextField();
        medicineSearch = new javax.swing.JComboBox<>();
        addMedicine = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        removeMedicine = new javax.swing.JButton();
        removeAllMedicine = new javax.swing.JButton();
        medicineTableScroll = new javax.swing.JScrollPane();
        medicineTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        UploadKey = new javax.swing.JButton();
        medicineQuantity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        createReceipt = new javax.swing.JButton();
        receipterror = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profileNameLabel = new javax.swing.JLabel();
        profileName = new javax.swing.JLabel();
        profileRegisterLabel = new javax.swing.JLabel();
        profileRegister = new javax.swing.JLabel();
        profileUsernameLabel = new javax.swing.JLabel();
        profileUsername = new javax.swing.JLabel();
        profileEmail = new javax.swing.JLabel();
        profileEmailLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        profileVerfiiedLabel = new javax.swing.JLabel();
        profileVerified = new javax.swing.JLabel();
        profilePhoneLabel = new javax.swing.JLabel();
        profilePhone = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        settingSidePanel = new javax.swing.JPanel();
        changePasswordLabel = new javax.swing.JLabel();
        helpLabel = new javax.swing.JLabel();
        reportLabel = new javax.swing.JLabel();
        helpIndicator = new javax.swing.JLabel();
        changePasswordIndicator = new javax.swing.JLabel();
        reportIndicator = new javax.swing.JLabel();
        settingDisplayPanel = new javax.swing.JPanel();
        changePasswordPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        currentPassword = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        newPassword = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        confirmNewPassword = new javax.swing.JTextField();
        changePasswordbutton = new javax.swing.JButton();
        settingErrorLabel = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        reportPanel = new javax.swing.JPanel();
        reportSubject = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        yourQuery = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        reportSumitbutton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        reportError = new javax.swing.JLabel();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sidemenu = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        homeIndicator = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        prescription = new javax.swing.JPanel();
        prescriptionIndicator = new javax.swing.JLabel();
        prescriptionLable = new javax.swing.JLabel();
        prescriptionIcon = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        profileIndicator = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        profileIcon = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        logoutIndicator = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(237, 238, 240));

        appointmentViews.setBackground(new java.awt.Color(255, 255, 255));

        patientTableModel = new DefaultTableModel(todisplayTable(),new String[]{"Name","Phone No.","Medicine","Time"});
        patientTable.setModel(patientTableModel);
        jScrollPane1.setViewportView(patientTable);

        javax.swing.GroupLayout tableViewPanelLayout = new javax.swing.GroupLayout(tableViewPanel);
        tableViewPanel.setLayout(tableViewPanelLayout);
        tableViewPanelLayout.setHorizontalGroup(
            tableViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        tableViewPanelLayout.setVerticalGroup(
            tableViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        appointmentNumValue.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        appointmentNumValue.setToolTipText("");

        appointementNumLabel.setBackground(new java.awt.Color(255, 255, 255));
        appointementNumLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        appointementNumLabel.setText("Today's Appointments:");

        oneMonthView.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        oneMonthView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oneMonthView.setText("1M");
        oneMonthView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMonthViewMouseClicked(evt);
            }
        });

        oneDayView.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        oneDayView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oneDayView.setText("1D");
        oneDayView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneDayViewMouseClicked(evt);
            }
        });

        fiveDayView.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        fiveDayView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiveDayView.setText("5D");
        fiveDayView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveDayViewMouseClicked(evt);
            }
        });

        sixMonthView.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        sixMonthView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sixMonthView.setText("6M");
        sixMonthView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMonthViewMouseClicked(evt);
            }
        });

        oneYearView.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        oneYearView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oneYearView.setText("1Y");
        oneYearView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneYearViewMouseClicked(evt);
            }
        });

        indicatorDate.setBackground(new java.awt.Color(0, 0, 0));
        indicatorDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        indicatorDate.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(appointementNumLabel)
                .addGap(12, 12, 12)
                .addComponent(appointmentNumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(387, 387, 387)
                .addComponent(oneYearView, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sixMonthView, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oneMonthView, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fiveDayView, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(oneDayView, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(850, 850, 850)
                .addComponent(indicatorDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointementNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(appointmentNumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiveDayView, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneMonthView, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixMonthView, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oneYearView, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(oneDayView, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(indicatorDate, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout appointmentViewsLayout = new javax.swing.GroupLayout(appointmentViews);
        appointmentViews.setLayout(appointmentViewsLayout);
        appointmentViewsLayout.setHorizontalGroup(
            appointmentViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tableViewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        appointmentViewsLayout.setVerticalGroup(
            appointmentViewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentViewsLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tableViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(appointmentViews, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(appointmentViews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        display.add(homePanel, "card2");

        prescriptionPanel.setBackground(new java.awt.Color(237, 238, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(66, 123, 214));
        jLabel7.setText("New Prescription");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        patientName.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 123, 214));
        jLabel3.setText("Patient Phone No.");

        patientPhNo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 123, 214));
        jLabel4.setText("Patient Age");

        patientAge.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        medicineSearch.setEditable(true);
        try{
            medicineSearch.setModel(new javax.swing.DefaultComboBoxModel<>(medicineResult()));
        } catch(IOException e){
            System.out.println(e);
        }
        AutoCompleteDecorator.decorate(medicineSearch);
        medicineSearch.setSelectedItem("");
        medicineSearch.setEditable(true);

        addMedicine.setText("Add");
        addMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicineActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 123, 214));
        jLabel5.setText("Patient Full Name");

        removeMedicine.setText("Remove");
        removeMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMedicineActionPerformed(evt);
            }
        });

        removeAllMedicine.setText("Remove all");
        removeAllMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllMedicineActionPerformed(evt);
            }
        });

        medicineTableModel = new DefaultTableModel(new String[][]{}, new String[]{"Medicine","Quantity"});
        medicineTable.setModel(medicineTableModel);
        medicineTable.setOpaque(false);
        medicineTable.setShowHorizontalLines(false);
        medicineTable.setShowVerticalLines(false);
        medicineTableScroll.setViewportView(medicineTable);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 123, 214));
        jLabel6.setText("Medicine");

        UploadKey.setBackground(new java.awt.Color(255, 255, 255));
        UploadKey.setForeground(new java.awt.Color(66, 123, 214));
        UploadKey.setText("Upload Private Key");
        UploadKey.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 123, 214)));
        UploadKey.setContentAreaFilled(false);
        UploadKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadKeyActionPerformed(evt);
            }
        });

        medicineQuantity.setAutoscrolls(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(66, 123, 214));
        jLabel11.setText("Quantity");

        createReceipt.setText("Create");
        createReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReceiptActionPerformed(evt);
            }
        });

        receipterror.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        receipterror.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(patientAge)
                                .addComponent(patientPhNo)
                                .addComponent(patientName)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(UploadKey, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                            .addComponent(medicineTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(medicineSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(medicineQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeMedicine)
                            .addComponent(addMedicine)
                            .addComponent(removeAllMedicine))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receipterror, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receipterror, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medicineSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(medicineQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(UploadKey, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(addMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(removeMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(removeAllMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(medicineTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(createReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout prescriptionPanelLayout = new javax.swing.GroupLayout(prescriptionPanel);
        prescriptionPanel.setLayout(prescriptionPanelLayout);
        prescriptionPanelLayout.setHorizontalGroup(
            prescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prescriptionPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(prescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        prescriptionPanelLayout.setVerticalGroup(
            prescriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prescriptionPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );

        display.add(prescriptionPanel, "card3");

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));

        profileNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        profileNameLabel.setText("Name:");

        profileName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        profileRegisterLabel.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        profileRegisterLabel.setText("Registration No:");

        profileRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        profileUsernameLabel.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        profileUsernameLabel.setText("Username:");

        profileUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        profileEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        profileEmailLabel.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        profileEmailLabel.setText("Email:");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userprofile.jpg"))); // NOI18N

        profileVerfiiedLabel.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        profileVerfiiedLabel.setText("Verified:");

        profileVerified.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        profilePhoneLabel.setFont(new java.awt.Font("Segoe UI", 3, 15)); // NOI18N
        profilePhoneLabel.setText("Phone No:");

        profilePhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profilePhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileVerfiiedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileRegisterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileUsernameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(profileUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(profileRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(profileVerified, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(267, 267, 267))
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileVerified, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileVerfiiedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilePhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        display.add(profilePanel, "card4");

        settingSidePanel.setBackground(new java.awt.Color(255, 255, 255));

        changePasswordLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        changePasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePasswordLabel.setText("Change Password");
        changePasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordLabelMouseClicked(evt);
            }
        });

        helpLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        helpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpLabel.setText("Help");
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });

        reportLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        reportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reportLabel.setText("Report");
        reportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportLabelMouseClicked(evt);
            }
        });

        helpIndicator.setBackground(new java.awt.Color(255, 255, 255));
        helpIndicator.setOpaque(true);

        changePasswordIndicator.setBackground(new java.awt.Color(0, 0, 0));
        changePasswordIndicator.setOpaque(true);

        reportIndicator.setBackground(new java.awt.Color(255, 255, 255));
        reportIndicator.setOpaque(true);

        javax.swing.GroupLayout settingSidePanelLayout = new javax.swing.GroupLayout(settingSidePanel);
        settingSidePanel.setLayout(settingSidePanelLayout);
        settingSidePanelLayout.setHorizontalGroup(
            settingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(helpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changePasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
            .addComponent(reportLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changePasswordIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reportIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        settingSidePanelLayout.setVerticalGroup(
            settingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingSidePanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(changePasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(changePasswordIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(helpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(helpIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(reportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(reportIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );

        settingDisplayPanel.setBackground(new java.awt.Color(255, 255, 255));
        settingDisplayPanel.setLayout(new java.awt.CardLayout());

        changePasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Current Password");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setText("Reset Password");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("New Password");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("Confirm New Password");

        changePasswordbutton.setBackground(new java.awt.Color(255, 255, 255));
        changePasswordbutton.setText("Change");
        changePasswordbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        changePasswordbutton.setContentAreaFilled(false);
        changePasswordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordbuttonActionPerformed(evt);
            }
        });

        settingErrorLabel.setBackground(new java.awt.Color(255, 255, 255));
        settingErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        settingErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout changePasswordPanelLayout = new javax.swing.GroupLayout(changePasswordPanel);
        changePasswordPanel.setLayout(changePasswordPanelLayout);
        changePasswordPanelLayout.setHorizontalGroup(
            changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPanelLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePasswordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmNewPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addComponent(settingErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        changePasswordPanelLayout.setVerticalGroup(
            changePasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(changePasswordbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        settingDisplayPanel.add(changePasswordPanel, "card2");

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        settingDisplayPanel.add(helpPanel, "card3");

        reportPanel.setBackground(new java.awt.Color(255, 255, 255));

        yourQuery.setColumns(20);
        yourQuery.setRows(5);
        jScrollPane2.setViewportView(yourQuery);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel17.setText("Subject");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel18.setText("Your Query");

        reportSumitbutton.setBackground(new java.awt.Color(255, 255, 255));
        reportSumitbutton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        reportSumitbutton.setText("Submit");
        reportSumitbutton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reportSumitbutton.setContentAreaFilled(false);
        reportSumitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSumitbuttonActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel16.setText("Report");

        reportError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        reportError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(reportSumitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(reportError, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addGap(37, 37, 37)
                .addComponent(reportError, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reportSumitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        settingDisplayPanel.add(reportPanel, "card4");

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(settingSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(settingDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(settingSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGap(54, 54, 54))
        );

        display.add(settingPanel, "card5");

        Logo.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cure-all");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        sidemenu.setBackground(new java.awt.Color(51, 51, 51));

        home.setBackground(new java.awt.Color(51, 51, 51));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeIndicator.setBackground(new java.awt.Color(255, 255, 255));
        homeIndicator.setOpaque(true);
        home.add(homeIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 48));

        homeLabel.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("Home");
        home.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 50));

        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeWhite.png"))); // NOI18N
        home.add(homeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        prescription.setBackground(new java.awt.Color(51, 51, 51));
        prescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescriptionMouseClicked(evt);
            }
        });
        prescription.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prescriptionIndicator.setBackground(new java.awt.Color(120, 120, 120));
        prescriptionIndicator.setOpaque(true);
        prescription.add(prescriptionIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 48));

        prescriptionLable.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        prescriptionLable.setForeground(new java.awt.Color(255, 255, 255));
        prescriptionLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prescriptionLable.setText("Prescription");
        prescription.add(prescriptionLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 190, 30));

        prescriptionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/receipt.png"))); // NOI18N
        prescription.add(prescriptionIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        profile.setBackground(new java.awt.Color(51, 51, 51));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileIndicator.setBackground(new java.awt.Color(120, 120, 120));
        profileIndicator.setOpaque(true);
        profile.add(profileIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 48));

        profileLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileLabel.setText("Profile");
        profile.add(profileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 100, 40));

        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        profile.add(profileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        logout.setBackground(new java.awt.Color(51, 51, 51));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutIndicator.setBackground(new java.awt.Color(168, 84, 84));
        logoutIndicator.setOpaque(true);
        logout.add(logoutIndicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 36));

        logoutLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(168, 84, 84));
        logoutLabel.setText("Log Out");
        logout.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, 76, 36));

        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        logout.add(logoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 0, -1, 36));

        setting.setBackground(new java.awt.Color(51, 51, 51));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });
        setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(93, 121, 166));
        jLabel9.setOpaque(true);
        setting.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(93, 121, 166));
        jLabel10.setText("Setting");
        setting.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting.png"))); // NOI18N
        setting.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 40));

        javax.swing.GroupLayout sidemenuLayout = new javax.swing.GroupLayout(sidemenu);
        sidemenu.setLayout(sidemenuLayout);
        sidemenuLayout.setHorizontalGroup(
            sidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidemenuLayout.createSequentialGroup()
                .addGroup(sidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prescription, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
            .addComponent(setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidemenuLayout.setVerticalGroup(
            sidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidemenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(prescription, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(setting, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidemenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sidemenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
       homeIndicator.setBackground(new Color(255,255,255));
       prescriptionIndicator.setBackground(new Color(120,120,120));
       profileIndicator.setBackground(new Color(120,120,120));
       homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeWhite.png")));
       prescriptionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/receipt.png")));
       profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png")));
       cardLayout.show(display,"card2");
    }//GEN-LAST:event_homeMouseClicked

    private void prescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescriptionMouseClicked
        homeIndicator.setBackground(new Color(120,120,120));
        prescriptionIndicator.setBackground(new Color(255,255,255));
        profileIndicator.setBackground(new Color(120,120,120));
        prescriptionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/receiptWhite.png")));
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png")));
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png")));
        cardLayout.show(display,"card3");

    }//GEN-LAST:event_prescriptionMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        homeIndicator.setBackground(new Color(120,120,120));
        prescriptionIndicator.setBackground(new Color(120,120,120));
        profileIndicator.setBackground(new Color(255,255,255));
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png")));
        prescriptionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/receipt.png")));
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profileWhite.png")));
        cardLayout.show(display,"card4");
    }//GEN-LAST:event_profileMouseClicked

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        homeIndicator.setBackground(new Color(120,120,120));
        prescriptionIndicator.setBackground(new Color(120,120,120));
        profileIndicator.setBackground(new Color(120,120,120));
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png")));
        prescriptionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/receipt.png")));
        profileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png")));
        cardLayout.show(display,"card5");
    }//GEN-LAST:event_settingMouseClicked

    private void addMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicineActionPerformed
        int index = medicineTableModel.getRowCount();
        String med = ((JTextField)medicineSearch.getEditor().getEditorComponent()).getText().strip();
        String quantity = medicineQuantity.getText();
        if(med.length()<4){
            receipterror.setText("*Add the medicine name");
            return;
        }
        if(quantity.length()==0 || Integer.parseInt(quantity)==0){
            receipterror.setText("*Add the appropriate quantity");
            return;
        }
        medicineList[index][0] = med;
        medicineList[index][1] = medicineQuantity.getText();
        medicineTableModel.addRow(new String[]{medicineList[index][0],medicineList[index][1]});
    }//GEN-LAST:event_addMedicineActionPerformed

    private void removeMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMedicineActionPerformed
        try {
            medicineTableModel.removeRow(medicineTable.getSelectedRow());
        } catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(removeAllMedicine,"Select a row to remove");
        }
    }//GEN-LAST:event_removeMedicineActionPerformed

    private void removeAllMedicineActionPerformed(java.awt.event.ActionEvent evt){
        removeAllMedicineActionPerformed();
    }
    private void removeAllMedicineActionPerformed() {//GEN-FIRST:event_removeAllMedicineActionPerformed
        for(int i=medicineTable.getRowCount()-1;i>=0;i--){
            medicineTableModel.removeRow(i);
        }
    }//GEN-LAST:event_removeAllMedicineActionPerformed

    private void UploadKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadKeyActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Key or Text", "txt", "key");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                    chooser.getSelectedFile());
        }
    }//GEN-LAST:event_UploadKeyActionPerformed

    private void createReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReceiptActionPerformed
        Pattern pattern = Pattern.compile("^(\\d{10})$");
        Matcher match = pattern.matcher(patientPhNo.getText());
        if(!match.matches()) {
            receipterror.setText("*Check the phone number");
            return;
        }
        pattern = Pattern.compile("^(\\d{1,3})$");
        match = pattern.matcher(patientAge.getText());
        if(!match.matches()){
            receipterror.setText("*Check the Age");
            return;
        }
        pattern = Pattern.compile("^\\w{3,10}\\s\\w{3,10}$");
        match = pattern.matcher(patientName.getText());
        if(!match.matches()){
            receipterror.setText("*Check the Name");
            return;
        }
        if(medicineTableModel.getRowCount()==0){
            receipterror.setText("*You haven't added any medicines");
            return;
        }

        String[] a = new String[medicineTableModel.getRowCount()];
        for(int i=0;i<a.length;i++) {
            if(medicineList[i][0] == null){
                break;
            }
            a[i] = medicineList[i][0] +" {"+medicineList[i][1]+"}";
        }
        boolean b = main.createReceipt(doctor.getRegistrationNo(),patientName.getText(),Integer.parseInt(patientAge.getText()),a,Long.parseLong(patientPhNo.getText()));
        if(!b){
            receipterror.setText("*You filled something wrong");
        }else{
            patientName.setText("");
            patientAge.setText("");
            receipterror.setText("");
            patientPhNo.setText("");
            medicineList = new String[10][2];
            removeAllMedicineActionPerformed();
            medicineQuantity.setText("");
            medicineSearch.setSelectedItem("");
            receipterror.setForeground(new java.awt.Color(7, 245, 67));
            receipterror.setText("*Receipt created");
            // Patient Updated patient data from the database
            Thread p = new Thread( () ->{
                try{
                    allDocPatientData = main.getPatientDataDoc(doctor.getRegistrationNo());
                    moveTimeIndicator(oneDayView.getBounds().x);
                    displayData("OneDay");
                }catch (Exception e){
                    System.out.println(e);
                }
            });
            p.start();
            Thread t = new Thread(() -> {       // to Remove the "receipt created" text from the displey
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                receipterror.setText("");
                receipterror.setForeground(new java.awt.Color(255, 51, 51));
            });
            t.start();
        }

        }//GEN-LAST:event_createReceiptActionPerformed

    private void oneYearViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneYearViewMouseClicked
        displayData("OneYear");
        moveTimeIndicator(oneYearView.getBounds().x);

    }//GEN-LAST:event_oneYearViewMouseClicked

    private void sixMonthViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMonthViewMouseClicked
        displayData("SixMonth");
        moveTimeIndicator(sixMonthView.getBounds().x);
    }//GEN-LAST:event_sixMonthViewMouseClicked

    private void oneMonthViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMonthViewMouseClicked
        displayData("OneMonth");
        moveTimeIndicator(oneMonthView.getBounds().x);
    }//GEN-LAST:event_oneMonthViewMouseClicked

    private void fiveDayViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveDayViewMouseClicked
        displayData("FiveDays");
        moveTimeIndicator(fiveDayView.getBounds().x);
    }//GEN-LAST:event_fiveDayViewMouseClicked

    private void oneDayViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneDayViewMouseClicked
        displayData("OneDay");
        moveTimeIndicator(oneDayView.getBounds().x);
    }//GEN-LAST:event_oneDayViewMouseClicked

    private void changePasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordLabelMouseClicked
        reportIndicator.setBackground(new Color(255,255,255));
        helpIndicator.setBackground(new Color(255,255,255));
        changePasswordIndicator.setBackground(new Color(0,0,0));
        settingLayout.show(settingDisplayPanel,"card2");
    }//GEN-LAST:event_changePasswordLabelMouseClicked

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        reportIndicator.setBackground(new Color(255,255,255));
        helpIndicator.setBackground(new Color(0,0,0));
        changePasswordIndicator.setBackground(new Color(255,255,255));
        settingLayout.show(settingDisplayPanel,"card3");

    }//GEN-LAST:event_helpLabelMouseClicked

    private void reportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseClicked
        reportIndicator.setBackground(new Color(0,0,0));
        helpIndicator.setBackground(new Color(255,255,255));
        changePasswordIndicator.setBackground(new Color(255,255,255));
        settingLayout.show(settingDisplayPanel,"card4");

    }//GEN-LAST:event_reportLabelMouseClicked

    private void changePasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordbuttonActionPerformed
        Pattern pattern = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@#$%^&*!=])(?=\\S+$).{8,}$");
        Matcher match = pattern.matcher(newPassword.getText());
        if(!match.matches()){
            settingErrorLabel.setText("Password should contain one Uppercase,lowercase,digit and a symbol");
        }
        if(newPassword.getText().equals(confirmNewPassword.getText())) {
            String a = main.changePassword(currentPassword.getText(), newPassword.getText(), doctor.getEmail(), "doctor");
            if(a.equals("Password has been changed")){
                settingErrorLabel.setForeground(new Color(51,255,0));
                settingErrorLabel.setText("*"+a);

            }else {
                settingErrorLabel.setForeground(new Color(255, 51, 51));
                settingErrorLabel.setText("*"+a);
            }
            new Thread(()->{
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                settingErrorLabel.setText("");
            }).start();
        }

    }//GEN-LAST:event_changePasswordbuttonActionPerformed

    private void reportSumitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSumitbuttonActionPerformed
        if(reportSubject.getText()==null){
            reportError.setText("*Fill the Subject");
        }else if(yourQuery.getText()==null){
            reportError.setText("*Write the query");
        }
        new Thread(()->{
            try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            reportError.setText("");
        }).start();
    }//GEN-LAST:event_reportSumitbuttonActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        signOut();
    }//GEN-LAST:event_logoutMouseClicked



    void moveTimeIndicator(int x){
        Rectangle r = indicatorDate.getBounds();
        new Thread(() -> {
            int i=r.x;
                double velocity = .005;
            boolean direction = false;           // MOVE IN LEFT DIRECTION MEANS FALSE
            if(i<x){
                direction = true;                   //  MOVE IN RIGHT DIRECTION MEANS TRUE
            }
            while(true){
                try {
                    Thread.sleep(5);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                indicatorDate.setBounds(i,r.y,r.width,r.height);
                if(direction){
                    if(i>x){
                        break;
                    }
                    i+= i*velocity;
                }else{
                    if(i<x)
                        break;
                    i-= i*velocity;
                }
            }
        }).start();
    }


    void displayData(String interval){
        docPatientData = sortedList(interval);
        patientTableModel = new DefaultTableModel(todisplayTable(),new String[]{"Name","Phone No.","Medicine","Time"});
        patientTable.setModel(patientTableModel);
    }
    String[][] todisplayTable(){
        appointmentNumValue.setText(String.valueOf(docPatientData.size()));
        if(docPatientData.size()==0){
            return new String[1][1];
        }
        String[][] patientTableData = new String[docPatientData.size()][4];
        for(int i=0;i<docPatientData.size();i++){
            Receipt r = docPatientData.get(i);
            patientTableData[i][0] = r.getPatientName();
            patientTableData[i][1] = String.valueOf(r.getPatientPhNo());
            patientTableData[i][2] = r.getMedicine();
            patientTableData[i][3] = String.valueOf(r.getGenerateTime());
        }
        return patientTableData;
    }
    ArrayList<Receipt> sortedList(String interval){
        ArrayList<Receipt> a = new ArrayList<>();
        Date date;
        if(allDocPatientData == null){
            return a;
        }
        if(allDocPatientData.size()==0){
            return a;
        }
        switch (interval) {
            case "OneYear" -> date = new Date(System.currentTimeMillis() - 365L * 24 * 3600 * 1000);
            case "OneMonth" -> date = new Date(System.currentTimeMillis() - 30L * 24 * 3600 * 1000);
            case "SixMonth" -> date = new Date(System.currentTimeMillis() - 182L * 24 * 3600 * 1000);
            case "FiveDays" -> date = new Date(System.currentTimeMillis() - 5L * 24 * 3600 * 1000);
            case "OneDay" -> date = new Date(System.currentTimeMillis() - 24 * 3600 * 1000);
            default -> throw new IllegalStateException("Unexpected value: " + interval);
        }
        for(Receipt r: allDocPatientData){
            if(r.getGenerateTime().after(date)){
                a.add(r);
            }
        }
        return a;
    }


    private String[] medicineResult() throws IOException {
        byte[] arr = new byte[10000000];
        InputStream is = DoctorDisplay.class.getResourceAsStream("/medicines.txt");
        is.read(arr);
        return new String(arr).split("\n");
    }

    private void displayProfile(){
        profileName.setText(doctor.getName());
        profileRegister.setText(String.valueOf(doctor.getRegistrationNo()));
        profileEmail.setText(doctor.getEmail());
        profileUsername.setText(doctor.getUsername());
        if(doctor.getPhoneNo()>10){
            profilePhone.setText(String.valueOf(doctor.getPhoneNo()));
        }else{
            profilePhone.setText("NA");
        }
        if(doctor.isVerified()){
            profileVerified.setText("Verified");
        }else{
            profileVerified.setText("Not Verified");
        }
    }

    private void signOut(){
        main.logout("doctor");
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JButton UploadKey;
    private javax.swing.JButton addMedicine;
    private javax.swing.JLabel appointementNumLabel;
    private javax.swing.JLabel appointmentNumValue;
    private javax.swing.JPanel appointmentViews;
    private javax.swing.JLabel changePasswordIndicator;
    private javax.swing.JLabel changePasswordLabel;
    private javax.swing.JPanel changePasswordPanel;
    private javax.swing.JButton changePasswordbutton;
    private javax.swing.JTextField confirmNewPassword;
    private javax.swing.JButton createReceipt;
    private javax.swing.JTextField currentPassword;
    private javax.swing.JPanel display;
    private javax.swing.JLabel fiveDayView;
    private javax.swing.JLabel helpIndicator;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JPanel home;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel homeIndicator;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel indicatorDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JLabel logoutIndicator;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField medicineQuantity;
    private javax.swing.JComboBox<String> medicineSearch;
    private javax.swing.JTable medicineTable;
    private javax.swing.JScrollPane medicineTableScroll;
    private javax.swing.JTextField newPassword;
    private javax.swing.JLabel oneDayView;
    private javax.swing.JLabel oneMonthView;
    private javax.swing.JLabel oneYearView;
    private javax.swing.JTextField patientAge;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField patientPhNo;
    private javax.swing.JTable patientTable;
    private javax.swing.JPanel prescription;
    private javax.swing.JLabel prescriptionIcon;
    private javax.swing.JLabel prescriptionIndicator;
    private javax.swing.JLabel prescriptionLable;
    private javax.swing.JPanel prescriptionPanel;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel profileEmail;
    private javax.swing.JLabel profileEmailLabel;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JLabel profileIndicator;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel profileName;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel profilePhone;
    private javax.swing.JLabel profilePhoneLabel;
    private javax.swing.JLabel profileRegister;
    private javax.swing.JLabel profileRegisterLabel;
    private javax.swing.JLabel profileUsername;
    private javax.swing.JLabel profileUsernameLabel;
    private javax.swing.JLabel profileVerfiiedLabel;
    private javax.swing.JLabel profileVerified;
    private javax.swing.JLabel receipterror;
    private javax.swing.JButton removeAllMedicine;
    private javax.swing.JButton removeMedicine;
    private javax.swing.JLabel reportError;
    private javax.swing.JLabel reportIndicator;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JTextField reportSubject;
    private javax.swing.JButton reportSumitbutton;
    private javax.swing.JPanel setting;
    private javax.swing.JPanel settingDisplayPanel;
    private javax.swing.JLabel settingErrorLabel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JPanel settingSidePanel;
    private javax.swing.JPanel sidemenu;
    private javax.swing.JLabel sixMonthView;
    private javax.swing.JPanel tableViewPanel;
    private javax.swing.JTextArea yourQuery;
    // End of variables declaration//GEN-END:variables
    private String[][] medicineList = new String[10][2];
    private DefaultTableModel medicineTableModel;
    private DefaultTableModel patientTableModel;
    private Main main = new Main();
    private Doctor doctor;
    private ArrayList<Receipt> docPatientData;
    private ArrayList<Receipt> allDocPatientData;
}
