/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Idms.main;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;
import java.util.concurrent.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Jitesh
 */
public class Login extends javax.swing.JFrame {

/**
 * Creates new form Login
 */

    final Main main = new Main();
    static String resetCode,username,person;
    CardLayout cardLayout = new CardLayout();
    ExecutorService service = Executors.newSingleThreadExecutor();
    boolean isResetPassword = false;
    boolean verified = true;
    public Login() {
//    this.setUndecorated(true);
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Windows".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(DoctorDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    initComponents();
//    this.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
    this.setLocationRelativeTo(null);
    cardLayout = (CardLayout)(loginSignPanel.getLayout());
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pharmacyPhoto = new javax.swing.JLabel();
        doctorPhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loginPage = new javax.swing.JPanel();
        loginIndicator = new javax.swing.JLabel();
        loginText = new javax.swing.JLabel();
        signUpPage = new javax.swing.JPanel();
        signUpIndicator = new javax.swing.JLabel();
        signUpText = new javax.swing.JLabel();
        loginSignPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        loginUsername = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginPassword = new javax.swing.JPasswordField();
        loginerror = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forgotPassword = new javax.swing.JLabel();
        showPasswordLogin = new javax.swing.JCheckBox();
        signUpPanel = new javax.swing.JPanel();
        signUpTitle = new javax.swing.JLabel();
        signUpNameLabel = new javax.swing.JLabel();
        signUpName = new javax.swing.JTextField();
        signUpEmailLabel = new javax.swing.JLabel();
        signUpEmail = new javax.swing.JTextField();
        regisNoLabel = new javax.swing.JLabel();
        signUpregisNo = new javax.swing.JTextField();
        signUpPasswordLabel = new javax.swing.JLabel();
        signUpCPasswordLabel = new javax.swing.JLabel();
        signUPbutton = new javax.swing.JButton();
        signUpCPassword = new javax.swing.JPasswordField();
        signUpPassword = new javax.swing.JPasswordField();
        signUperror = new javax.swing.JLabel();
        showPasswordSignUp = new javax.swing.JCheckBox();
        verificationPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        verifyEmailinput = new javax.swing.JTextField();
        verifyErrorLabel = new javax.swing.JLabel();
        sendEmailButton = new javax.swing.JButton();
        resendTimerLabel = new javax.swing.JLabel();
        verifyCodePanel = new javax.swing.JPanel();
        verificationCodeLabel = new javax.swing.JLabel();
        verificationCodeInput = new javax.swing.JTextField();
        codeVerifyButton = new javax.swing.JButton();
        resetPasswordPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JButton();
        resetPassworderror = new javax.swing.JLabel();
        cResetPassIn = new javax.swing.JPasswordField();
        resetPassIn = new javax.swing.JPasswordField();
        showPasswordReset = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(147, 138, 250));

        pharmacyPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pharmacyPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy.jpg"))); // NOI18N
        pharmacyPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        pharmacyPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pharmacyPhotoMouseClicked(evt);
            }
        });

        doctorPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor.jpg"))); // NOI18N
        doctorPhoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        doctorPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorPhotoMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(147, 138, 250));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Drug-Store");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pill.png"))); // NOI18N
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(doctorPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(pharmacyPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doctorPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pharmacyPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        loginPage.setBackground(new java.awt.Color(255, 255, 255));
        loginPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginPageMouseClicked(evt);
            }
        });

        loginIndicator.setBackground(new java.awt.Color(147, 138, 250));
        loginIndicator.setOpaque(true);

        loginText.setBackground(new java.awt.Color(255, 255, 255));
        loginText.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        loginText.setForeground(new java.awt.Color(204, 204, 204));
        loginText.setText("Login");

        javax.swing.GroupLayout loginPageLayout = new javax.swing.GroupLayout(loginPage);
        loginPage.setLayout(loginPageLayout);
        loginPageLayout.setHorizontalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPageLayout.createSequentialGroup()
                .addComponent(loginIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        loginPageLayout.setVerticalGroup(
            loginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        signUpPage.setBackground(new java.awt.Color(255, 255, 255));
        signUpPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpPageMouseClicked(evt);
            }
        });

        signUpIndicator.setBackground(new java.awt.Color(255, 255, 255));
        signUpIndicator.setOpaque(true);

        signUpText.setBackground(new java.awt.Color(255, 255, 255));
        signUpText.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        signUpText.setForeground(new java.awt.Color(204, 204, 204));
        signUpText.setText("Sign Up");

        javax.swing.GroupLayout signUpPageLayout = new javax.swing.GroupLayout(signUpPage);
        signUpPage.setLayout(signUpPageLayout);
        signUpPageLayout.setHorizontalGroup(
            signUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPageLayout.createSequentialGroup()
                .addComponent(signUpIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpText)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        signUpPageLayout.setVerticalGroup(
            signUpPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUpIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(signUpText, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signUpPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(loginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(loginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(signUpPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        loginSignPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginSignPanel.setLayout(new java.awt.CardLayout());
        loginSignPanel.setLayout(cardLayout);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Email or Username");

        loginUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(147, 138, 250));
        loginButton.setText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(147, 138, 255), new java.awt.Color(147, 138, 255), new java.awt.Color(147, 138, 255), new java.awt.Color(147, 138, 255)));
        loginButton.setContentAreaFilled(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Password");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Login");

        loginPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        loginerror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginerror.setForeground(new java.awt.Color(255, 51, 51));
        loginerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setText("Forgot Password?");

        forgotPassword.setForeground(new java.awt.Color(51, 102, 255));
        forgotPassword.setText("Click Here");
        forgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseClicked(evt);
            }
        });

        showPasswordLogin.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordLogin.setText("Show Password");
        showPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(278, 278, 278))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(loginerror, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addComponent(loginUsername))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPassword)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(forgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(48, 48, 48))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(loginerror, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showPasswordLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(forgotPassword))
                .addGap(127, 127, 127))
        );

        loginSignPanel.add(loginPanel, "card2");

        signUpPanel.setBackground(new java.awt.Color(255, 255, 255));

        signUpTitle.setBackground(new java.awt.Color(255, 255, 255));
        signUpTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        signUpTitle.setForeground(new java.awt.Color(204, 204, 204));
        signUpTitle.setText("Sign Up");

        signUpNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        signUpNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        signUpNameLabel.setForeground(new java.awt.Color(204, 204, 204));
        signUpNameLabel.setText("Name");

        signUpName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        signUpEmailLabel.setBackground(new java.awt.Color(255, 255, 255));
        signUpEmailLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        signUpEmailLabel.setForeground(new java.awt.Color(204, 204, 204));
        signUpEmailLabel.setText("Email Id");

        signUpEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        regisNoLabel.setBackground(new java.awt.Color(255, 255, 255));
        regisNoLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        regisNoLabel.setForeground(new java.awt.Color(204, 204, 204));
        regisNoLabel.setText("Registration No");

        signUpregisNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        signUpPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        signUpPasswordLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        signUpPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        signUpPasswordLabel.setText("Password");

        signUpCPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        signUpCPasswordLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        signUpCPasswordLabel.setForeground(new java.awt.Color(204, 204, 204));
        signUpCPasswordLabel.setText("Confirm Password");

        signUPbutton.setBackground(new java.awt.Color(255, 255, 255));
        signUPbutton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        signUPbutton.setForeground(new java.awt.Color(147, 138, 250));
        signUPbutton.setText("Sign Up");
        signUPbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(147, 138, 255), new java.awt.Color(147, 138, 255), new java.awt.Color(147, 138, 255), new java.awt.Color(147, 138, 255)));
        signUPbutton.setContentAreaFilled(false);
        signUPbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUPbuttonMouseClicked(evt);
            }
        });

        signUpCPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        signUpPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        signUperror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signUperror.setForeground(new java.awt.Color(255, 51, 51));

        showPasswordSignUp.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordSignUp.setText("Show Password");
        showPasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(signUperror, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(signUpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(signUPbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signUpPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regisNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpCPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(signUpregisNo)
                            .addComponent(signUpCPassword)
                            .addComponent(signUpEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(signUpPassword))
                        .addComponent(showPasswordSignUp))
                    .addComponent(signUpName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(signUpTitle)
                .addGap(18, 18, 18)
                .addComponent(signUperror, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signUpName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signUpNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(signUpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(signUpEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpregisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regisNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUpCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpCPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showPasswordSignUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(signUPbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        loginSignPanel.add(signUpPanel, "card3");

        verificationPanel.setBackground(new java.awt.Color(255, 255, 255));
        verificationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Email Verification");
        verificationPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 61, 223, 41));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Email Address or Username");
        verificationPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 155, 217, -1));

        verifyEmailinput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verificationPanel.add(verifyEmailinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 186, 223, 28));

        verifyErrorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verifyErrorLabel.setForeground(new java.awt.Color(255, 51, 51));
        verifyErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verificationPanel.add(verifyErrorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 121, 330, 15));

        sendEmailButton.setText("Send");
        sendEmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailButtonActionPerformed(evt);
            }
        });
        verificationPanel.add(sendEmailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 66, -1));

        resendTimerLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resendTimerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verificationPanel.add(resendTimerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 55, 20));

        verifyCodePanel.setBackground(new java.awt.Color(255, 255, 255));
        verifyCodePanel.setVisible(false);

        verificationCodeLabel.setBackground(new java.awt.Color(255, 255, 255));
        verificationCodeLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        verificationCodeLabel.setText("Verfication Code");

        verificationCodeInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        codeVerifyButton.setText("Verify");
        codeVerifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeVerifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verifyCodePanelLayout = new javax.swing.GroupLayout(verifyCodePanel);
        verifyCodePanel.setLayout(verifyCodePanelLayout);
        verifyCodePanelLayout.setHorizontalGroup(
            verifyCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyCodePanelLayout.createSequentialGroup()
                .addGroup(verifyCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verifyCodePanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(verifyCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verificationCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(verifyCodePanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(verificationCodeLabel))))
                    .addGroup(verifyCodePanelLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(codeVerifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        verifyCodePanelLayout.setVerticalGroup(
            verifyCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyCodePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(verificationCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verificationCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codeVerifyButton)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        verificationPanel.add(verifyCodePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 276, -1, -1));

        loginSignPanel.add(verificationPanel, "card4");

        resetPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setText("Reset Password");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("New Password");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Confirm Password");

        changePasswordButton.setText("Submit");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        resetPassworderror.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetPassworderror.setForeground(new java.awt.Color(255, 51, 51));
        resetPassworderror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cResetPassIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        resetPassIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        showPasswordReset.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordReset.setText("Show Password");
        showPasswordReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetPasswordPanelLayout = new javax.swing.GroupLayout(resetPasswordPanel);
        resetPasswordPanel.setLayout(resetPasswordPanelLayout);
        resetPasswordPanelLayout.setHorizontalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(resetPassIn)
                        .addComponent(cResetPassIn))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPasswordReset))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPasswordPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(resetPassworderror, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resetPasswordPanelLayout.setVerticalGroup(
            resetPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(resetPassworderror, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(resetPassIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cResetPassIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(showPasswordReset)
                .addGap(18, 18, 18)
                .addComponent(changePasswordButton)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        loginSignPanel.add(resetPasswordPanel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(loginSignPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginSignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPageMouseClicked
        new Thread(()->{
            loginIndicator.setBackground(new Color(147,138,250));
            signUpIndicator.setBackground(new Color(255,255,255));
        }).start();
        loginPassword.setText("");
        loginUsername.setText("");
        cardLayout.show(loginSignPanel,"card2");
    }//GEN-LAST:event_loginPageMouseClicked

    private void signUpPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpPageMouseClicked
        signUpPassword.setText("");
        signUpEmail.setText("");
        signUpCPassword.setText("");
        signUpName.setText("");
        signUpregisNo.setText("");
        cardLayout.show(loginSignPanel,"card3");
        new Thread(()->{
            signUpIndicator.setBackground(new Color(147,138,250));
            loginIndicator.setBackground(new Color(255,255,255));
        }).start();

    }//GEN-LAST:event_signUpPageMouseClicked



    private void signUPbuttonMouseClicked(java.awt.event.MouseEvent evt)  {//GEN-FIRST:event_signUPbuttonMouseClicked
        String password = new String(signUpPassword.getPassword());
        String cpassword = new String(signUpCPassword.getPassword());
        String email = signUpEmail.getText();
        String regisNo = signUpregisNo.getText();
        String name = signUpName.getText();
        Pattern pattern = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@#$%^&*!=])(?=\\S+$).{8,}$");
        Matcher match = pattern.matcher(password);
        if(regisNo.length()<6){
            signUperror.setText("*Invalid Registration No or Gst No");
            return;
        }
        if(!match.matches()){
            signUperror.setText("Password should contain one Uppercase,lowercase,digit and a symbol");
            return;
        }
        if(!password.equals(cpassword)){
            signUperror.setText("*Password did not match");
            return;
        }
        if(person==null){
            signUperror.setText("*Please select your occupation");
            return;
        }
        try{
            String a = main.createUser(person, name, email, password, regisNo);

            if (a.substring(a.length() - 6, a.length() - 1).equals("email")) {
                signUperror.setText("*Email already registered");
            }
            if (a.substring(a.length() - 8, a.length() - 1).equals("PRIMARY")) {
                signUperror.setText("*Registration No or Gst No already registered");
            }
            if(a.startsWith("Inserted")){
                verifyErrorLabel.setForeground(new Color(49, 191, 49));
                verifyErrorLabel.setText("*Successful signed up");
                verifyEmailinput.setText(email);
//                verifyEmailinput.setEnabled(false);
                cardLayout.show(loginSignPanel,"card4");
                verified = false;
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        if(signUperror.getText().length()>0) {
            new Thread(() -> {
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                signUperror.setText("");
            }).start();
        }
    }//GEN-LAST:event_signUPbuttonMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        Pattern pattern = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@#$%^&*!=])(?=\\S+$).{8,}$");
        Matcher match = pattern.matcher(Arrays.toString(loginPassword.getPassword()));
        loginerror.setForeground(new Color(255,51,0));
        if(loginUsername.getText().length()<6){
            loginerror.setText("*Incorrect Username");
            return;
        }else if(match.matches()){
            loginerror.setText("*Invalid Password");
            return;
        }
        if(person==null){
            loginerror.setText("*Please select your occupation");
            return;
        }
        try {
            String email = loginUsername.getText();
            String a = main.verifyLogin(person,email, new String(loginPassword.getPassword()));
            if(a.equals("notVerified")){
                verified = false;
                verifyEmailinput.setText(email);
                cardLayout.show(loginSignPanel,"card4");
                verifyErrorLabel.setText("*Please Verify your email first");
                return;
            }
            loginerror.setText(a);
        }catch(Exception e){
            e.printStackTrace();
        }
        if(loginerror.getText().length()>0) {
            new Thread(() -> {
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                loginerror.setText("");
            }).start();
        }
    }//GEN-LAST:event_loginButtonActionPerformed



    private void doctorPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorPhotoMouseClicked
        doctorPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctortick.jpg")));
        pharmacyPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy.jpg")));
        regisNoLabel.setText("Registration No.");
        person = "doctor" ;

    }//GEN-LAST:event_doctorPhotoMouseClicked



    private void pharmacyPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmacyPhotoMouseClicked

            pharmacyPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacytick.jpg")));
            doctorPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doctor.jpg")));
            regisNoLabel.setText("GST No.");
            person = "pharmacy";
    }//GEN-LAST:event_pharmacyPhotoMouseClicked

    private void showPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordLoginActionPerformed
        if(showPasswordLogin.isSelected()){
            loginPassword.setEchoChar((char)0);
            showPasswordLogin.setSelected(true);
        }else{
            loginPassword.setEchoChar('\u25cf');
            showPasswordLogin.setSelected(false);
        }
    }//GEN-LAST:event_showPasswordLoginActionPerformed


    private void showPasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordSignUpActionPerformed
        if(showPasswordSignUp.isSelected()){
            signUpPassword.setEchoChar((char)0);
            signUpCPassword.setEchoChar((char)0);
            showPasswordSignUp.setSelected(true);
        }else{
            signUpPassword.setEchoChar('\u25cf');
            signUpCPassword.setEchoChar('\u25cf');
            showPasswordSignUp.setSelected(false);
        }
    }//GEN-LAST:event_showPasswordSignUpActionPerformed


    private void forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordMouseClicked
        cardLayout.show(loginSignPanel,"card4");
        isResetPassword = true;
        verifyEmailinput.setText("");
        sendEmailButton.setText("Send");
        verificationCodeInput.setText("");
    }//GEN-LAST:event_forgotPasswordMouseClicked



    private void sendEmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailButtonActionPerformed
        username = verifyEmailinput.getText();
        verifyErrorLabel.setForeground(new Color(248, 31, 31));
        if(person==null){
            verifyErrorLabel.setText("*Please select the occupation");
            return;
        }
        if(username.length()<6){
            verifyErrorLabel.setText("*Incorrect email");
        }else {
            String a = main.sendPasswordMail(username);
            if (a.equals("*User doesn't exist") || a.equals("*Email or username is not registered")) {
                verifyErrorLabel.setText(a);
            } else {
                verifyErrorLabel.setForeground(new Color(0, 245, 51));
                verifyCodePanel.setVisible(true);
                resetCode = a;
                verifyErrorLabel.setText("Check your mail");
                sendEmailButton.setEnabled(false);
                sendEmailButton.setText("Resend");
                try {
                    service.awaitTermination(1, TimeUnit.SECONDS);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                Thread timer = new Thread(()->{
                    String b="min";
                    int min,sec;
                   for(int i=120;i>=0;i--){
                       if(i<61){
                           b = "sec";
                       }
                       try {
                           Thread.sleep(1000);
                       } catch (InterruptedException e) {
                           e.printStackTrace();
                       }
                       min = i/60;
                       sec = i%60;
                       resendTimerLabel.setText(min+":"+String.format("%02d",sec)+" "+b);
                   }
                   sendEmailButton.setEnabled(true);
                   resendTimerLabel.setText("");
                });
                service.execute(timer);
            }
        }
        if(verifyErrorLabel.getText().length()>0){
            new Thread(() -> {
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException e) {
                    System.out.println(e.toString());
                }
                verifyErrorLabel.setText("");
            }).start();
        }
    }//GEN-LAST:event_sendEmailButtonActionPerformed


    private void codeVerifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeVerifyButtonActionPerformed
        if(verificationCodeInput.getText().equals(resetCode)){
            if(!verified)
                main.verifyUser(person,username);
            verified = true;
            if(isResetPassword)
                cardLayout.show(loginSignPanel,"card5");
            else{
                loginPassword.setText("");
                loginUsername.setText("");
                cardLayout.show(loginSignPanel,"card2");
                loginerror.setForeground(new Color(0, 245, 51));
                loginerror.setText("You have been Verified!");
            }
            verifyEmailinput.setText("");


        }else{
            verifyErrorLabel.setText("*Invalid Code");
        }
        verificationCodeInput.setText("");
    }//GEN-LAST:event_codeVerifyButtonActionPerformed


    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        service.shutdown();
        String pass = new String(resetPassIn.getPassword());
        String cpass = new String(cResetPassIn.getPassword());
        Pattern pattern = Pattern.compile("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@#$%^&*!=])(?=\\S+$).{8,}$");
        Matcher match = pattern.matcher(pass);
        
        if(!match.matches()) {
            resetPassworderror.setText("*Password should contain 1 Uppercase,1 Lowercase,1 Special char,1 Digit");
            return;
        }
        if(!pass.equals(cpass)){
            resetPassworderror.setText("*Your Password don't match");
            return;
        }
        isResetPassword = false;
        String a =  main.resetPassword(pass,username,person);
        if(a.equals("Password has been changed")){
            loginPassword.setText("");
            loginUsername.setText("");
            cardLayout.show(loginSignPanel,"card2");
            loginerror.setText(a);
            loginerror.setForeground(new Color(0, 245, 51));
            new Thread(()->{
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                loginerror.setText("");
            }).start();
        }else{
            resetPassworderror.setText(a);
        }
        if(resetPassworderror.getText().length()>0){
            new Thread(() -> {
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException e) {
                    System.out.println(e.toString());
                }
                resetPassworderror.setText("");
            }).start();
        }
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void showPasswordResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordResetActionPerformed
        if(showPasswordReset.isSelected()){
            resetPassIn.setEchoChar((char)0);
            cResetPassIn.setEchoChar((char)0);
            showPasswordSignUp.setSelected(true);
        }else{
            resetPassIn.setEchoChar('\u25cf');
            cResetPassIn.setEchoChar('\u25cf');
            showPasswordSignUp.setSelected(false);
        }
    }//GEN-LAST:event_showPasswordResetActionPerformed





/**
 * @param args the command line arguments
 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cResetPassIn;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JButton codeVerifyButton;
    private javax.swing.JLabel doctorPhoto;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginIndicator;
    private javax.swing.JPanel loginPage;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JPanel loginSignPanel;
    private javax.swing.JLabel loginText;
    private javax.swing.JTextField loginUsername;
    private javax.swing.JLabel loginerror;
    private javax.swing.JLabel pharmacyPhoto;
    private javax.swing.JLabel regisNoLabel;
    private javax.swing.JLabel resendTimerLabel;
    private javax.swing.JPasswordField resetPassIn;
    private javax.swing.JPanel resetPasswordPanel;
    private javax.swing.JLabel resetPassworderror;
    private javax.swing.JButton sendEmailButton;
    private javax.swing.JCheckBox showPasswordLogin;
    private javax.swing.JCheckBox showPasswordReset;
    private javax.swing.JCheckBox showPasswordSignUp;
    private javax.swing.JButton signUPbutton;
    private javax.swing.JPasswordField signUpCPassword;
    private javax.swing.JLabel signUpCPasswordLabel;
    private javax.swing.JTextField signUpEmail;
    private javax.swing.JLabel signUpEmailLabel;
    private javax.swing.JLabel signUpIndicator;
    private javax.swing.JTextField signUpName;
    private javax.swing.JLabel signUpNameLabel;
    private javax.swing.JPanel signUpPage;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JPasswordField signUpPassword;
    private javax.swing.JLabel signUpPasswordLabel;
    private javax.swing.JLabel signUpText;
    private javax.swing.JLabel signUpTitle;
    private javax.swing.JLabel signUperror;
    private javax.swing.JTextField signUpregisNo;
    private javax.swing.JTextField verificationCodeInput;
    private javax.swing.JLabel verificationCodeLabel;
    private javax.swing.JPanel verificationPanel;
    private javax.swing.JPanel verifyCodePanel;
    private javax.swing.JTextField verifyEmailinput;
    private javax.swing.JLabel verifyErrorLabel;
    // End of variables declaration//GEN-END:variables

}
