/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Idms.main;

import com.Idms.beans.Pharma;

import java.awt.*;

/**
 *
 * @author Jitesh
 */
public class PharmacyDisplay extends javax.swing.JFrame {

    /**
     * Creates new form PharmacyDisplay
     */
    boolean dashBool;
    boolean profileBool;
    boolean drugBool;
    public PharmacyDisplay() {
        initComponents();
        dashBool = true;
        profileBool = false;
        drugBool = false;
    }
    public PharmacyDisplay(Pharma pharma) {
        initComponents();
        dashBool = true;
        profileBool = false;
        drugBool = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JPanel();
        dashIndicator = new javax.swing.JLabel();
        dashBoardLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JPanel();
        profileIndicator = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        drugButton = new javax.swing.JPanel();
        drugIndicator = new javax.swing.JLabel();
        drugLabel = new javax.swing.JLabel();
        settingbutton = new javax.swing.JPanel();
        settingIndicator = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        drugPanel = new javax.swing.JPanel();
        settingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(51, 51, 51));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardButton.setOpaque(false);
        dashboardButton.setPreferredSize(new java.awt.Dimension(260, 50));
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
        });

        dashIndicator.setBackground(new java.awt.Color(255, 255, 255));
        dashIndicator.setOpaque(true);

        dashBoardLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        dashBoardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardWhite.png"))); // NOI18N
        dashBoardLabel.setText("DashBoard");
        dashBoardLabel.setIconTextGap(30);

        javax.swing.GroupLayout dashboardButtonLayout = new javax.swing.GroupLayout(dashboardButton);
        dashboardButton.setLayout(dashboardButtonLayout);
        dashboardButtonLayout.setHorizontalGroup(
            dashboardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardButtonLayout.createSequentialGroup()
                .addComponent(dashIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(dashBoardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dashboardButtonLayout.setVerticalGroup(
            dashboardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashBoardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidePanel.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 260, -1));

        profileButton.setOpaque(false);
        profileButton.setPreferredSize(new java.awt.Dimension(260, 50));
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
        });

        profileIndicator.setBackground(new java.awt.Color(51, 51, 51));
        profileIndicator.setOpaque(true);

        profileLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        profileLabel.setText("Profile");
        profileLabel.setIconTextGap(30);

        javax.swing.GroupLayout profileButtonLayout = new javax.swing.GroupLayout(profileButton);
        profileButton.setLayout(profileButtonLayout);
        profileButtonLayout.setHorizontalGroup(
            profileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileButtonLayout.createSequentialGroup()
                .addComponent(profileIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        profileButtonLayout.setVerticalGroup(
            profileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        drugButton.setOpaque(false);
        drugButton.setPreferredSize(new java.awt.Dimension(260, 50));
        drugButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugButtonMouseClicked(evt);
            }
        });

        drugIndicator.setBackground(new java.awt.Color(51, 51, 51));
        drugIndicator.setOpaque(true);

        drugLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        drugLabel.setForeground(new java.awt.Color(255, 255, 255));
        drugLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png"))); // NOI18N
        drugLabel.setText("Drugs");
        drugLabel.setIconTextGap(30);

        javax.swing.GroupLayout drugButtonLayout = new javax.swing.GroupLayout(drugButton);
        drugButton.setLayout(drugButtonLayout);
        drugButtonLayout.setHorizontalGroup(
            drugButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugButtonLayout.createSequentialGroup()
                .addComponent(drugIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(drugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        drugButtonLayout.setVerticalGroup(
            drugButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drugIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drugLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(drugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        settingbutton.setOpaque(false);
        settingbutton.setPreferredSize(new java.awt.Dimension(260, 50));

        settingIndicator.setBackground(new java.awt.Color(93, 121, 166));
        settingIndicator.setOpaque(true);

        settingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        settingLabel.setForeground(new java.awt.Color(93, 121, 166));
        settingLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting.png"))); // NOI18N
        settingLabel.setText("Setting");
        settingLabel.setIconTextGap(30);

        javax.swing.GroupLayout settingbuttonLayout = new javax.swing.GroupLayout(settingbutton);
        settingbutton.setLayout(settingbuttonLayout);
        settingbuttonLayout.setHorizontalGroup(
            settingbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingbuttonLayout.createSequentialGroup()
                .addComponent(settingIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        settingbuttonLayout.setVerticalGroup(
            settingbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(settingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidePanel.add(settingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        logoutButton.setOpaque(false);
        logoutButton.setPreferredSize(new java.awt.Dimension(260, 50));

        jLabel9.setBackground(new java.awt.Color(168, 84, 84));
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(168, 84, 84));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jLabel10.setText("Logout");
        jLabel10.setIconTextGap(30);

        javax.swing.GroupLayout logoutButtonLayout = new javax.swing.GroupLayout(logoutButton);
        logoutButton.setLayout(logoutButtonLayout);
        logoutButtonLayout.setHorizontalGroup(
            logoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutButtonLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        logoutButtonLayout.setVerticalGroup(
            logoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidePanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        displayPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        displayPanel.add(dashboardPanel, "card2");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        displayPanel.add(profilePanel, "card3");

        javax.swing.GroupLayout drugPanelLayout = new javax.swing.GroupLayout(drugPanel);
        drugPanel.setLayout(drugPanelLayout);
        drugPanelLayout.setHorizontalGroup(
            drugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        drugPanelLayout.setVerticalGroup(
            drugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        displayPanel.add(drugPanel, "card4");

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        displayPanel.add(settingPanel, "card5");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked
        if(!dashBool){
            new Thread(()->{
                dashIndicator.setBackground(new Color(255,255,255));
                profileIndicator.setBackground(new Color(51,51,51));
                drugIndicator.setBackground(new Color(51,51,51));
                dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardWhite.png")));
                profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png")));
                drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png")));

            }).start();
            dashBool = true;
            profileBool = false;
            drugBool = false;
        }
    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
        if(!profileBool){
            new Thread(()->{
                profileIndicator.setBackground(new Color(255,255,255));
                dashIndicator.setBackground(new Color(51,51,51));
                drugIndicator.setBackground(new Color(51,51,51));
                dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png")));
                profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userWhite.png")));
                drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png")));

            }).start();
            dashBool = false;
            profileBool = true;
            drugBool = false;
        }
    }//GEN-LAST:event_profileButtonMouseClicked

    private void drugButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugButtonMouseClicked
        if(!drugBool){
            new Thread(()->{
                drugIndicator.setBackground(new Color(255,255,255));
                profileIndicator.setBackground(new Color(51,51,51));
                dashIndicator.setBackground(new Color(51,51,51));
                dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png")));
                profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png")));
                drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalWhite.png")));

            }).start();
            dashBool = false;
            profileBool = false;
            drugBool = true;
        }
    }//GEN-LAST:event_drugButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashBoardLabel;
    private javax.swing.JLabel dashIndicator;
    private javax.swing.JPanel dashboardButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel drugButton;
    private javax.swing.JLabel drugIndicator;
    private javax.swing.JLabel drugLabel;
    private javax.swing.JPanel drugPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel profileButton;
    private javax.swing.JLabel profileIndicator;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel settingIndicator;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JPanel settingbutton;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
