/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Idms.main;

import com.Idms.beans.Pharma;
import com.Idms.beans.Receipt;

import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author Jitesh
 */
public class PharmacyDisplay extends javax.swing.JFrame {

    /**
     * Creates new form PharmacyDisplay
     */
    Main main;
    Pharma pharma;
    CardLayout mainCardLayout = new CardLayout();
    boolean dashBool;
    boolean profileBool;
    boolean drugBool;
    boolean settingBool;
    private DefaultTableModel custModel;
    public PharmacyDisplay() {
        initComponents();
        dashBool = true;
        profileBool = false;
        drugBool = false;
    }
    public PharmacyDisplay(Pharma pharma) {
        this.pharma =  pharma;
        this.main = new Main();
        displayCustomer();
        initComponents();
        dashBool = true;
        profileBool = false;
        drugBool = false;
        settingBool = false;
        mainCardLayout = (CardLayout) (displayPanel.getLayout());
        displayProfile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        dashboardButton = new javax.swing.JPanel();
        dashIndicator = new javax.swing.JLabel();
        dashBoardLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JPanel();
        profileIndicator = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        drugButton = new javax.swing.JPanel();
        drugIndicator = new javax.swing.JLabel();
        drugLabel = new javax.swing.JLabel();
        settingbutton = new javax.swing.JPanel();
        settingIndicator = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalCustomer = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        oneMonth = new javax.swing.JLabel();
        oneWeek = new javax.swing.JLabel();
        oneDay = new javax.swing.JLabel();
        tweleveHours = new javax.swing.JLabel();
        slider = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profileNameLabel = new javax.swing.JLabel();
        profileName = new javax.swing.JLabel();
        profileEmailLabel = new javax.swing.JLabel();
        profileUsernameLabel = new javax.swing.JLabel();
        profileVerifiedLabel = new javax.swing.JLabel();
        profilePhoneLabel = new javax.swing.JLabel();
        profileEmail = new javax.swing.JLabel();
        profileUsername = new javax.swing.JLabel();
        profileGst = new javax.swing.JLabel();
        profilePhone = new javax.swing.JLabel();
        profileImage = new javax.swing.JLabel();
        profileGstLabel = new javax.swing.JLabel();
        profileVerified = new javax.swing.JLabel();
        drugPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        phoneSearch = new javax.swing.JTextField();
        drugPersonDetails = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugTable = new javax.swing.JTable();
        phoneSearchButton = new javax.swing.JButton();
        drugError = new javax.swing.JLabel();
        drugMedicineError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        settingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(51, 51, 51));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardButton.setOpaque(false);
        dashboardButton.setPreferredSize(new java.awt.Dimension(260, 50));
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
        });

        dashIndicator.setBackground(new java.awt.Color(255, 255, 255));
        dashIndicator.setOpaque(true);

        dashBoardLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        dashBoardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardWhite.png"))); // NOI18N
        dashBoardLabel.setText("DashBoard");
        dashBoardLabel.setIconTextGap(30);

        javax.swing.GroupLayout dashboardButtonLayout = new javax.swing.GroupLayout(dashboardButton);
        dashboardButton.setLayout(dashboardButtonLayout);
        dashboardButtonLayout.setHorizontalGroup(
            dashboardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardButtonLayout.createSequentialGroup()
                .addComponent(dashIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(dashBoardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dashboardButtonLayout.setVerticalGroup(
            dashboardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashBoardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidePanel.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 260, -1));

        profileButton.setOpaque(false);
        profileButton.setPreferredSize(new java.awt.Dimension(260, 50));
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
        });

        profileIndicator.setBackground(new java.awt.Color(51, 51, 51));
        profileIndicator.setOpaque(true);

        profileLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        profileLabel.setText("Profile");
        profileLabel.setIconTextGap(30);

        javax.swing.GroupLayout profileButtonLayout = new javax.swing.GroupLayout(profileButton);
        profileButton.setLayout(profileButtonLayout);
        profileButtonLayout.setHorizontalGroup(
            profileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileButtonLayout.createSequentialGroup()
                .addComponent(profileIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(profileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        profileButtonLayout.setVerticalGroup(
            profileButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        drugButton.setOpaque(false);
        drugButton.setPreferredSize(new java.awt.Dimension(260, 50));
        drugButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugButtonMouseClicked(evt);
            }
        });

        drugIndicator.setBackground(new java.awt.Color(51, 51, 51));
        drugIndicator.setOpaque(true);

        drugLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        drugLabel.setForeground(new java.awt.Color(255, 255, 255));
        drugLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png"))); // NOI18N
        drugLabel.setText("Drugs");
        drugLabel.setIconTextGap(30);

        javax.swing.GroupLayout drugButtonLayout = new javax.swing.GroupLayout(drugButton);
        drugButton.setLayout(drugButtonLayout);
        drugButtonLayout.setHorizontalGroup(
            drugButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugButtonLayout.createSequentialGroup()
                .addComponent(drugIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(drugLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        drugButtonLayout.setVerticalGroup(
            drugButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drugIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drugLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(drugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        settingbutton.setOpaque(false);
        settingbutton.setPreferredSize(new java.awt.Dimension(260, 50));
        settingbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingbuttonMouseClicked(evt);
            }
        });

        settingIndicator.setBackground(new java.awt.Color(93, 121, 166));
        settingIndicator.setOpaque(true);

        settingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        settingLabel.setForeground(new java.awt.Color(93, 121, 166));
        settingLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting.png"))); // NOI18N
        settingLabel.setText("Setting");
        settingLabel.setIconTextGap(30);

        javax.swing.GroupLayout settingbuttonLayout = new javax.swing.GroupLayout(settingbutton);
        settingbutton.setLayout(settingbuttonLayout);
        settingbuttonLayout.setHorizontalGroup(
            settingbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingbuttonLayout.createSequentialGroup()
                .addComponent(settingIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        settingbuttonLayout.setVerticalGroup(
            settingbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(settingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidePanel.add(settingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        logoutButton.setOpaque(false);
        logoutButton.setPreferredSize(new java.awt.Dimension(260, 50));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(168, 84, 84));
        jLabel9.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(168, 84, 84));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jLabel10.setText("Logout");
        jLabel10.setIconTextGap(30);

        javax.swing.GroupLayout logoutButtonLayout = new javax.swing.GroupLayout(logoutButton);
        logoutButton.setLayout(logoutButtonLayout);
        logoutButtonLayout.setHorizontalGroup(
            logoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutButtonLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        logoutButtonLayout.setVerticalGroup(
            logoutButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidePanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        displayPanel.setBackground(new java.awt.Color(255, 255, 255));
        displayPanel.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        totalCustomer.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        totalCustomer.setText("Total Customer:");

        totalAmount.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        totalAmount.setText("Total Amount:");

        oneMonth.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        oneMonth.setText("1M");

        oneWeek.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        oneWeek.setText("1W");

        oneDay.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        oneDay.setText("1D");

        tweleveHours.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tweleveHours.setText("12H");

        slider.setBackground(new java.awt.Color(0, 0, 0));
        slider.setOpaque(true);

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(totalCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(740, 740, 740)
                        .addComponent(oneMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(oneWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(oneDay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tweleveHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(830, 830, 830)
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneDay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tweleveHours, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        displayPanel.add(dashboardPanel, "card2");

        profilePanel.setBackground(new java.awt.Color(255, 255, 255));

        profileNameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profileNameLabel.setText("Name");

        profileName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        profileEmailLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profileEmailLabel.setText("Email:");

        profileUsernameLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profileUsernameLabel.setText("Username:");

        profileVerifiedLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profileVerifiedLabel.setText("Verified:");

        profilePhoneLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profilePhoneLabel.setText("Phone No:");

        profileEmail.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        profileUsername.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        profileGst.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        profilePhone.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        profileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userprofile.jpg"))); // NOI18N

        profileGstLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        profileGstLabel.setText("GST No:");

        profileVerified.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(profileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileVerifiedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profilePhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profileGstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(profileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profilePhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileGst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileVerified, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilePhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileVerifiedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileVerified, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileGstLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileGst, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        displayPanel.add(profilePanel, "card3");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Phone No:");

        drugPersonDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        drugTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null,null},
                {null, null, null,null},
                {null, null, null,null},
                {null, null, null,null}
            },
            new String [] {
                "Medicine", "Quantity", "Cost per piece","Total Cost"
            }
        ));
        drugTable.setColumnSelectionAllowed(true);
        drugTable.setGridColor(new java.awt.Color(255, 255, 255));
        drugTable.setOpaque(false);
        drugTable.setSelectionBackground(new java.awt.Color(51, 153, 255));
        drugTable.setShowHorizontalLines(false);
        drugTable.setShowVerticalLines(false);
        jScrollPane2.setViewportView(drugTable);

        phoneSearchButton.setBackground(new java.awt.Color(255, 255, 255));
        phoneSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phoneSearchButton.setText("Search");
        phoneSearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        phoneSearchButton.setContentAreaFilled(false);
        phoneSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneSearchButtonActionPerformed(evt);
            }
        });

        drugError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        drugError.setForeground(new java.awt.Color(255, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Total Bill:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Checkout");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drugError, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phoneSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(drugPersonDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(drugMedicineError, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(drugError, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phoneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(phoneSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(drugMedicineError, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(drugPersonDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout drugPanelLayout = new javax.swing.GroupLayout(drugPanel);
        drugPanel.setLayout(drugPanelLayout);
        drugPanelLayout.setHorizontalGroup(
            drugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        drugPanelLayout.setVerticalGroup(
            drugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        displayPanel.add(drugPanel, "card4");

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        displayPanel.add(settingPanel, "card5");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked
        if(!dashBool){
            new Thread(()->{
                dashIndicator.setBackground(new Color(255,255,255));
                profileIndicator.setBackground(new Color(51,51,51));
                drugIndicator.setBackground(new Color(51,51,51));
                dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardWhite.png")));
                profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png")));
                drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png")));
                mainCardLayout.show(displayPanel,"card2");
            }).start();
            dashBool = true;
            profileBool = false;
            drugBool = false;
            settingBool = false;
        }
    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
        if(!profileBool){
            new Thread(()->{
                profileIndicator.setBackground(new Color(255,255,255));
                dashIndicator.setBackground(new Color(51,51,51));
                drugIndicator.setBackground(new Color(51,51,51));
                dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png")));
                profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userWhite.png")));
                drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png")));
                mainCardLayout.show(displayPanel,"card3");
            }).start();
            dashBool = false;
            profileBool = true;
            drugBool = false;
            settingBool = false;
        }
    }//GEN-LAST:event_profileButtonMouseClicked

    private void drugButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugButtonMouseClicked
        if(!drugBool){
            new Thread(()->{
                drugIndicator.setBackground(new Color(255,255,255));
                profileIndicator.setBackground(new Color(51,51,51));
                dashIndicator.setBackground(new Color(51,51,51));
                dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png")));
                profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png")));
                drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalWhite.png")));
                mainCardLayout.show(displayPanel,"card4");
            }).start();
            dashBool = false;
            profileBool = false;
            drugBool = true;
            settingBool = false;
        }
    }//GEN-LAST:event_drugButtonMouseClicked

    private void settingbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingbuttonMouseClicked
        if(!settingBool){
            new Thread(()->{
                drugIndicator.setBackground(new Color(51,51,51));
                profileIndicator.setBackground(new Color(51,51,51));
                dashIndicator.setBackground(new Color(51,51,51));
                dashBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.png")));
                profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png")));
                drugLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalWhite.png")));
                mainCardLayout.show(displayPanel,"card5");
            }).start();
            dashBool = false;
            profileBool = false;
            drugBool = false;
            settingBool = true;
        }
    }//GEN-LAST:event_settingbuttonMouseClicked

    private void phoneSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneSearchButtonActionPerformed
        String temp = phoneSearch.getText();
        if(temp.length()==10){
            Receipt receipt = main.searchReceipt(Long.parseLong(temp));
            if(receipt==null){
                drugError.setText("*No Prescription");
                return;
            }
            drugPersonDetails.setText("<html>Name: "+receipt.getPatientName()+"<br>Age: "+receipt.getPatientAge()+"<br>Phone No: "+receipt.getPatientPhNo()+"</html>");
            displayMed(receipt);
        }else{
            drugError.setText("*Invalid");
        }
        if(drugError.getText().length()>0) {
            new Thread(() -> {
                try {
                    Thread.sleep(4000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                drugError.setText("");
            }).start();
        }
    }//GEN-LAST:event_phoneSearchButtonActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        main.logout("pharmacy");
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void displayMed(Receipt receipt){
        String[] meds = receipt.getMedicine().split(",");
        String[][] values = new String[meds.length][4];
        for(int i=0;i<values.length;i++){
            String[] temp = meds[i].split(" ");
            values[i][0] = temp[0];
            values[i][1] = temp[1];
            values[i][2] = null;
            values[i][3] = null;
        }
        custModel = new DefaultTableModel(values,new String[]{"Medicine","Quantity","Cost/Med","Total Cost"});

        drugTable.setModel(custModel);
    }


    public void displayProfile(){
        if(pharma!=null){
            new Thread(()->{
                profileEmail.setText(pharma.getEmail());
                profileName.setText(pharma.getName());
                profileUsername.setText(pharma.getMedStoreId());
                profileGst.setText(pharma.getGstNo());
                if(pharma.getPhoneNo()>10){
                    profilePhone.setText(String.valueOf(pharma.getPhoneNo()));
                }else{
                    profilePhone.setText("NA");
                }
                profileVerified.setText(pharma.isVerified()?"Verified":"Not Verified");
            }).start();
        }
    }

    private void displayCustomer(){
//        System.out.print(pharma.getCustomer());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashBoardLabel;
    private javax.swing.JLabel dashIndicator;
    private javax.swing.JPanel dashboardButton;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel drugButton;
    private javax.swing.JLabel drugError;
    private javax.swing.JLabel drugIndicator;
    private javax.swing.JLabel drugLabel;
    private javax.swing.JLabel drugMedicineError;
    private javax.swing.JPanel drugPanel;
    private javax.swing.JLabel drugPersonDetails;
    private javax.swing.JTable drugTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel logoutButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel oneDay;
    private javax.swing.JLabel oneMonth;
    private javax.swing.JLabel oneWeek;
    private javax.swing.JTextField phoneSearch;
    private javax.swing.JButton phoneSearchButton;
    private javax.swing.JPanel profileButton;
    private javax.swing.JLabel profileEmail;
    private javax.swing.JLabel profileEmailLabel;
    private javax.swing.JLabel profileGst;
    private javax.swing.JLabel profileGstLabel;
    private javax.swing.JLabel profileImage;
    private javax.swing.JLabel profileIndicator;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JLabel profileName;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel profilePhone;
    private javax.swing.JLabel profilePhoneLabel;
    private javax.swing.JLabel profileUsername;
    private javax.swing.JLabel profileUsernameLabel;
    private javax.swing.JLabel profileVerified;
    private javax.swing.JLabel profileVerifiedLabel;
    private javax.swing.JLabel settingIndicator;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JPanel settingbutton;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel slider;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JLabel totalCustomer;
    private javax.swing.JLabel tweleveHours;
    // End of variables declaration//GEN-END:variables
}
